### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by fregante** [bluwy/refined-github-comments#2]
Hello, I just saw this userscript and it looks great! However I was confused by its name when I saw it on Twitter, it sounds like an extension or feature of Refined GitHub. Would it be possible to rename it?

**Comment by bluwy** [comment]
Hey! I actually referenced the name from https://github.com/antfu/refined-github-notifications and https://github.com/patak-dev/refined-github-reactions. I'm happy to rename it if you feel that it's confusing with Refined GitHub. Is there a reason you closed the issue?

**Comment by fregante** [comment]
Oh thanks for pointing those out, they seem new too. I will open issues there too ☺️ 



> Is there a reason you closed the issue?

I didn't want this to be an issue, it's just a suggestion rather than a request. 🙏

**Comment by antfu** [comment]
Oh, hi @fregante! I love Refined GitHub, thank you a lot for maintaining it! I think I am the one who is responsible for choosing the naming. I took that name kinda in the spirit of tributing Refind GitHub, which I use day to day. While to me, I think refining GitHub is a general term as we are improving different aspect, or the pain points we have faced. I'd be happy to contribute back to Refined GitHub but my concern is that my needs are a bit opinionated that might not work for everyone.

That said, if you already have such conventions to distribute rules/extensions to Refined GitHub, I'd be happy to rename it to avoid conflicts. Otherwise, I also consider the current name ok, as we clearly stated we are userscripts in the README.

Let me know what you think. And thanks for all the work!

**Comment by patak-cat** [comment]
Seconded, thanks a lot for refined-github @fregante. It helps us so much. I agree with @antfu, and want to add to that in the case of https://github.com/patak-dev/refined-github-reactions, if you like the idea and refined-github ends up doing something similar in the future I'm more than happy to deprecate the repo and point folks your way. To do the same for the huge userbase of refined-github, it may require a bit more polishing to handle some spacing edge cases. And I also feel like Anthony that it may be too opinionated.

**Comment by fregante** [comment]
> I'd be happy to contribute back to Refined GitHub but my concern is that my needs are a bit opinionated that might not work for everyone.

Yeah it's often best to just build Userscripts rather than merge everything into RGH, especially for scripts that take automated actions like `refined-github-notifications`, so don't worry about not contributing.

**Comment by bluwy** [comment]
For me, I also followed the `refined-github-*` convention in hopes that I'll upstream some of the ideas in the future, that way I can remove features here and tell users that it's already supported builtin. It also means I'm developing the userscript with/for `refined-github` only, so it won't always work if `refined-github` is not installed, which the name helps to hint.
